#!/bin/bash
#SBATCH -A cc3uv3p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J auto-particle-gpu
#SBATCH -o auto-particle-gpu.stdout
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:k80:1
#SBATCH -t 00:30:00
#SBATCH -N 1         

./gpu -n 50000 
./gpu -n 100000 
./gpu -n 200000 
./gpu -n 400000 
./gpu -n 800000 
./serial -n 50000 -no
./serial -n 100000 -no
./serial -n 200000 -no
./serial -n 400000 -no
./serial -n 800000 -no
