#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug
#SBATCH -N 64
#SBATCH -t 00:30:00
#SBATCH -J auto-cori-debugging 
#SBATCH -o auto-cori-debugging.%j.stdout 
#SBATCH -J auto-cori-debugging.%j.error

srun -n 64 -N 64 ./PIC1p1D.exe -no -s mpi.txt
