#!/bin/bash -l
#SBATCH -A cc3uv3p
#SBATCH -p RM
#SBATCH -N 12
#SBATCH -t 00:10:00
#SBATCH -J auto-mpi32
#SBATCH -o auto-mpi32.%j.stdout
#SBATCH -e auto-mpi32.%j.error
#SBATCH --ntasks-per-node 1

rm -f mpi.txt
export I_MPI_JOB_RESPECT_PROCESS_PLACEMENT=0
mpirun -np $SLURM_NNODES ./mpi -n 50000 -no -o mpi.txt
mpirun -np $SLURM_NNODES ./mpi -n 100000 -no -o mpi.txt
mpirun -np $SLURM_NNODES ./mpi -n 200000 -no -o mpi.txt
mpirun -np $SLURM_NNODES ./mpi -n 400000 -no -o mpi.txt
mpirun -np $SLURM_NNODES ./mpi -n 800000 -no -o mpi.txt
