#!/bin/bash -l
#SBATCH -A cc3uv3p
#SBATCH -p RM
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -J auto-openmp32
#SBATCH -o auto-openmp32.%j.stdout
#SBATCH -e auto-openmp32.%j.error

rm -f openmp.txt
export OMP_NUM_THREADS=32
srun -N 1 -n 1 -c 32 ./openmp -n 50000 -no -o openmp.txt
srun -N 1 -n 1 -c 32 ./openmp -n 100000 -no -o openmp.txt
srun -N 1 -n 1 -c 32 ./openmp -n 200000 -no -o openmp.txt
srun -N 1 -n 1 -c 32 ./openmp -n 400000 -no -o openmp.txt
srun -N 1 -n 1 -c 32 ./openmp -n 800000 -no -o openmp.txt
