#!/bin/bash -l
#SBATCH -A cc3uv3p
#SBATCH -p RM
#SBATCH -N 12
#SBATCH -t 00:10:00
#SBATCH -J mpi32
#SBATCH -o mpi32.%j.stdout
#SBATCH -e mpi32.%j.error
#SBATCH --ntasks-per-node 1

export I_MPI_JOB_RESPECT_PROCESS_PLACEMENT=0
mpirun -np 12 ./mpi -n 50000 -o mpi.txt
