#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -J auto-cori-debugging 
#SBATCH -o auto-cori-valgrind.%j.stdout 
#SBATCH -J auto-cori-valgrind.%j.error

module load valgrind
srun -n 1 -N 1 -c 1 valgrind --leak-check=yes --track-origins=yes ./PIC2p2D.exe
