#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:20:00
#SBATCH -J auto-cori-debugging 
#SBATCH -o auto-cori-debugging.%j.stdout 
#SBATCH -J auto-cori-debugging.%j.error

rm mpi.txt
srun -n 1 -N 1 ./PIC2p2D.exe -no -s mpi.txt
